### ISSUE TITLE
LaTeX Error: File `jesse_resume.sty' not found.

### ISSUE THREAD

**Issue by tasdikrahman** [doy/resume#1]
Hey @doy 

Really liked the format on the pdf, but couldn't compile it. Gives me

 `! LaTeX Error: File 'jesse_resume.sty' not found.`

Any help on that?

**Comment by doy** [comment]
Oh, sorry, that probably depends on a few things from here https://github.com/doy/conf/tree/master/tex - I should probably copy them over at some point.
